import { createFileRoute } from '@tanstack/react-router';
import { supabaseAdmin } from '@/integrations/supabase/client.server';
import { buildIcs, type CalendarEvent } from '@/lib/calendar';

export const Route = createFileRoute('/api/public/calendar/$token')({
  server: {
    handlers: {
      GET: async ({ params }) => {
        const token = params.token;
        if (!token || token.length < 16) {
          return new Response('Not found', { status: 404 });
        }

        // Look up the owning user by their calendar_token
        const { data: profile, error: pErr } = await supabaseAdmin
          .from('profiles')
          .select('user_id, first_name, last_name')
          .eq('calendar_token', token)
          .maybeSingle();

        if (pErr || !profile) {
          return new Response('Not found', { status: 404 });
        }

        // Fetch this user's meetings (next ~90 days + last 7)
        const from = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();
        const to = new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString();

        const { data: meetings, error: mErr } = await supabaseAdmin
          .from('meetings')
          .select(
            `id,title,notes,scheduled_at,duration_minutes,
             company:companies!meetings_company_id_fkey(name,domain),
             contact:contacts!meetings_contact_id_fkey(first_name,last_name,title)`
          )
          .eq('user_id', profile.user_id)
          .gte('scheduled_at', from)
          .lte('scheduled_at', to)
          .order('scheduled_at', { ascending: true });

        if (mErr) {
          return new Response('Error', { status: 500 });
        }

        const events: CalendarEvent[] = (meetings ?? []).map((m: any) => {
          const parts: string[] = [];
          if (m.company?.name) parts.push(`Account: ${m.company.name}`);
          if (m.contact?.first_name)
            parts.push(
              `Contact: ${m.contact.first_name} ${m.contact.last_name ?? ''}${m.contact.title ? ` (${m.contact.title})` : ''}`,
            );
          if (m.notes) parts.push('', m.notes);
          parts.push('', 'Generated by Rexxon AI');
          return {
            id: m.id,
            title: m.title,
            description: parts.join('\n'),
            startISO: m.scheduled_at,
            durationMinutes: m.duration_minutes ?? 30,
            location: m.company?.domain ?? null,
          };
        });

        const name =
          [profile.first_name, profile.last_name].filter(Boolean).join(' ') || 'Rexxon';
        const ics = buildIcs(events, `${name} — Rexxon meetings`);

        return new Response(ics, {
          status: 200,
          headers: {
            'Content-Type': 'text/calendar; charset=utf-8',
            'Cache-Control': 'private, max-age=300',
            'Content-Disposition': 'inline; filename="rexxon-meetings.ics"',
          },
        });
      },
    },
  },
});
