/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TerritoryRouteImport } from './routes/territory'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubprocessorsRouteImport } from './routes/subprocessors'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ScheduleDemoRouteImport } from './routes/schedule-demo'
import { Route as RfpsRouteImport } from './routes/rfps'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PressRouteImport } from './routes/press'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BirdseyeRouteImport } from './routes/birdseye'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsIndexRouteImport } from './routes/accounts.index'
import { Route as ProposalsHistoryRouteImport } from './routes/proposals.history'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AccountsIdRouteImport } from './routes/accounts.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicCalendarTokenRouteImport } from './routes/api/public/calendar.$token'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TerritoryRoute = TerritoryRouteImport.update({
  id: '/territory',
  path: '/territory',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubprocessorsRoute = SubprocessorsRouteImport.update({
  id: '/subprocessors',
  path: '/subprocessors',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleDemoRoute = ScheduleDemoRouteImport.update({
  id: '/schedule-demo',
  path: '/schedule-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const RfpsRoute = RfpsRouteImport.update({
  id: '/rfps',
  path: '/rfps',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BirdseyeRoute = BirdseyeRouteImport.update({
  id: '/birdseye',
  path: '/birdseye',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsHistoryRoute = ProposalsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ProposalsRoute,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AccountsIdRoute = AccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCalendarTokenRoute = ApiPublicCalendarTokenRouteImport.update({
  id: '/api/public/calendar/$token',
  path: '/api/public/calendar/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/affiliates': typeof AffiliatesRoute
  '/analytics': typeof AnalyticsRoute
  '/birdseye': typeof BirdseyeRoute
  '/blog': typeof BlogRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/dpa': typeof DpaRoute
  '/help': typeof HelpRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/outreach': typeof OutreachRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/proposals': typeof ProposalsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/rfps': typeof RfpsRoute
  '/schedule-demo': typeof ScheduleDemoRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/subprocessors': typeof SubprocessorsRoute
  '/terms': typeof TermsRoute
  '/territory': typeof TerritoryRoute
  '/today': typeof TodayRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/proposals/history': typeof ProposalsHistoryRoute
  '/accounts/': typeof AccountsIndexRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/affiliates': typeof AffiliatesRoute
  '/analytics': typeof AnalyticsRoute
  '/birdseye': typeof BirdseyeRoute
  '/blog': typeof BlogRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/dpa': typeof DpaRoute
  '/help': typeof HelpRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/outreach': typeof OutreachRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/proposals': typeof ProposalsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/rfps': typeof RfpsRoute
  '/schedule-demo': typeof ScheduleDemoRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/subprocessors': typeof SubprocessorsRoute
  '/terms': typeof TermsRoute
  '/territory': typeof TerritoryRoute
  '/today': typeof TodayRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/proposals/history': typeof ProposalsHistoryRoute
  '/accounts': typeof AccountsIndexRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/affiliates': typeof AffiliatesRoute
  '/analytics': typeof AnalyticsRoute
  '/birdseye': typeof BirdseyeRoute
  '/blog': typeof BlogRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/dpa': typeof DpaRoute
  '/help': typeof HelpRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/outreach': typeof OutreachRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/proposals': typeof ProposalsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/rfps': typeof RfpsRoute
  '/schedule-demo': typeof ScheduleDemoRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/subprocessors': typeof SubprocessorsRoute
  '/terms': typeof TermsRoute
  '/territory': typeof TerritoryRoute
  '/today': typeof TodayRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/proposals/history': typeof ProposalsHistoryRoute
  '/accounts/': typeof AccountsIndexRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/affiliates'
    | '/analytics'
    | '/birdseye'
    | '/blog'
    | '/campaigns'
    | '/careers'
    | '/case-studies'
    | '/changelog'
    | '/checkout'
    | '/contact'
    | '/contacts'
    | '/cookies'
    | '/dashboard'
    | '/docs'
    | '/dpa'
    | '/help'
    | '/knowledge'
    | '/login'
    | '/outreach'
    | '/press'
    | '/privacy'
    | '/proposals'
    | '/reset-password'
    | '/rfps'
    | '/schedule-demo'
    | '/security'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/status'
    | '/subprocessors'
    | '/terms'
    | '/territory'
    | '/today'
    | '/accounts/$id'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/proposals/history'
    | '/accounts/'
    | '/api/public/calendar/$token'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/affiliates'
    | '/analytics'
    | '/birdseye'
    | '/blog'
    | '/campaigns'
    | '/careers'
    | '/case-studies'
    | '/changelog'
    | '/checkout'
    | '/contact'
    | '/contacts'
    | '/cookies'
    | '/dashboard'
    | '/docs'
    | '/dpa'
    | '/help'
    | '/knowledge'
    | '/login'
    | '/outreach'
    | '/press'
    | '/privacy'
    | '/proposals'
    | '/reset-password'
    | '/rfps'
    | '/schedule-demo'
    | '/security'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/status'
    | '/subprocessors'
    | '/terms'
    | '/territory'
    | '/today'
    | '/accounts/$id'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/proposals/history'
    | '/accounts'
    | '/api/public/calendar/$token'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/affiliates'
    | '/analytics'
    | '/birdseye'
    | '/blog'
    | '/campaigns'
    | '/careers'
    | '/case-studies'
    | '/changelog'
    | '/checkout'
    | '/contact'
    | '/contacts'
    | '/cookies'
    | '/dashboard'
    | '/docs'
    | '/dpa'
    | '/help'
    | '/knowledge'
    | '/login'
    | '/outreach'
    | '/press'
    | '/privacy'
    | '/proposals'
    | '/reset-password'
    | '/rfps'
    | '/schedule-demo'
    | '/security'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/status'
    | '/subprocessors'
    | '/terms'
    | '/territory'
    | '/today'
    | '/accounts/$id'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/proposals/history'
    | '/accounts/'
    | '/api/public/calendar/$token'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AffiliatesRoute: typeof AffiliatesRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BirdseyeRoute: typeof BirdseyeRoute
  BlogRoute: typeof BlogRouteWithChildren
  CampaignsRoute: typeof CampaignsRoute
  CareersRoute: typeof CareersRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ContactsRoute: typeof ContactsRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  DpaRoute: typeof DpaRoute
  HelpRoute: typeof HelpRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  OutreachRoute: typeof OutreachRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  ProposalsRoute: typeof ProposalsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  RfpsRoute: typeof RfpsRoute
  ScheduleDemoRoute: typeof ScheduleDemoRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatusRoute: typeof StatusRoute
  SubprocessorsRoute: typeof SubprocessorsRoute
  TermsRoute: typeof TermsRoute
  TerritoryRoute: typeof TerritoryRoute
  TodayRoute: typeof TodayRoute
  AccountsIdRoute: typeof AccountsIdRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  ApiPublicCalendarTokenRoute: typeof ApiPublicCalendarTokenRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/territory': {
      id: '/territory'
      path: '/territory'
      fullPath: '/territory'
      preLoaderRoute: typeof TerritoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subprocessors': {
      id: '/subprocessors'
      path: '/subprocessors'
      fullPath: '/subprocessors'
      preLoaderRoute: typeof SubprocessorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule-demo': {
      id: '/schedule-demo'
      path: '/schedule-demo'
      fullPath: '/schedule-demo'
      preLoaderRoute: typeof ScheduleDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfps': {
      id: '/rfps'
      path: '/rfps'
      fullPath: '/rfps'
      preLoaderRoute: typeof RfpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birdseye': {
      id: '/birdseye'
      path: '/birdseye'
      fullPath: '/birdseye'
      preLoaderRoute: typeof BirdseyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals/history': {
      id: '/proposals/history'
      path: '/history'
      fullPath: '/proposals/history'
      preLoaderRoute: typeof ProposalsHistoryRouteImport
      parentRoute: typeof ProposalsRoute
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/accounts/$id': {
      id: '/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar/$token': {
      id: '/api/public/calendar/$token'
      path: '/api/public/calendar/$token'
      fullPath: '/api/public/calendar/$token'
      preLoaderRoute: typeof ApiPublicCalendarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

interface ProposalsRouteChildren {
  ProposalsHistoryRoute: typeof ProposalsHistoryRoute
}

const ProposalsRouteChildren: ProposalsRouteChildren = {
  ProposalsHistoryRoute: ProposalsHistoryRoute,
}

const ProposalsRouteWithChildren = ProposalsRoute._addFileChildren(
  ProposalsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AffiliatesRoute: AffiliatesRoute,
  AnalyticsRoute: AnalyticsRoute,
  BirdseyeRoute: BirdseyeRoute,
  BlogRoute: BlogRouteWithChildren,
  CampaignsRoute: CampaignsRoute,
  CareersRoute: CareersRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ContactsRoute: ContactsRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  DpaRoute: DpaRoute,
  HelpRoute: HelpRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  OutreachRoute: OutreachRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  ProposalsRoute: ProposalsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  RfpsRoute: RfpsRoute,
  ScheduleDemoRoute: ScheduleDemoRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatusRoute: StatusRoute,
  SubprocessorsRoute: SubprocessorsRoute,
  TermsRoute: TermsRoute,
  TerritoryRoute: TerritoryRoute,
  TodayRoute: TodayRoute,
  AccountsIdRoute: AccountsIdRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  ApiPublicCalendarTokenRoute: ApiPublicCalendarTokenRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
