/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TerritoryRouteImport } from './routes/territory'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleDemoRouteImport } from './routes/schedule-demo'
import { Route as RfpsRouteImport } from './routes/rfps'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BirdseyeRouteImport } from './routes/birdseye'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsIndexRouteImport } from './routes/accounts.index'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AccountsIdRouteImport } from './routes/accounts.$id'
import { Route as ApiPublicCalendarTokenDoticsRouteImport } from './routes/api/public/calendar.$token[.]ics'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TerritoryRoute = TerritoryRouteImport.update({
  id: '/territory',
  path: '/territory',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleDemoRoute = ScheduleDemoRouteImport.update({
  id: '/schedule-demo',
  path: '/schedule-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const RfpsRoute = RfpsRouteImport.update({
  id: '/rfps',
  path: '/rfps',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BirdseyeRoute = BirdseyeRouteImport.update({
  id: '/birdseye',
  path: '/birdseye',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AccountsIdRoute = AccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalendarTokenDoticsRoute =
  ApiPublicCalendarTokenDoticsRouteImport.update({
    id: '/api/public/calendar/$token.ics',
    path: '/api/public/calendar/$token.ics',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/affiliates': typeof AffiliatesRoute
  '/analytics': typeof AnalyticsRoute
  '/birdseye': typeof BirdseyeRoute
  '/blog': typeof BlogRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/outreach': typeof OutreachRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rfps': typeof RfpsRoute
  '/schedule-demo': typeof ScheduleDemoRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/territory': typeof TerritoryRoute
  '/today': typeof TodayRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/accounts/': typeof AccountsIndexRoute
  '/api/public/calendar/$token.ics': typeof ApiPublicCalendarTokenDoticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/affiliates': typeof AffiliatesRoute
  '/analytics': typeof AnalyticsRoute
  '/birdseye': typeof BirdseyeRoute
  '/blog': typeof BlogRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/outreach': typeof OutreachRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rfps': typeof RfpsRoute
  '/schedule-demo': typeof ScheduleDemoRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/territory': typeof TerritoryRoute
  '/today': typeof TodayRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/accounts': typeof AccountsIndexRoute
  '/api/public/calendar/$token.ics': typeof ApiPublicCalendarTokenDoticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/affiliates': typeof AffiliatesRoute
  '/analytics': typeof AnalyticsRoute
  '/birdseye': typeof BirdseyeRoute
  '/blog': typeof BlogRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/outreach': typeof OutreachRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rfps': typeof RfpsRoute
  '/schedule-demo': typeof ScheduleDemoRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/territory': typeof TerritoryRoute
  '/today': typeof TodayRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/accounts/': typeof AccountsIndexRoute
  '/api/public/calendar/$token.ics': typeof ApiPublicCalendarTokenDoticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/affiliates'
    | '/analytics'
    | '/birdseye'
    | '/blog'
    | '/campaigns'
    | '/case-studies'
    | '/checkout'
    | '/contacts'
    | '/dashboard'
    | '/login'
    | '/outreach'
    | '/reset-password'
    | '/rfps'
    | '/schedule-demo'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/territory'
    | '/today'
    | '/accounts/$id'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/accounts/'
    | '/api/public/calendar/$token.ics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/affiliates'
    | '/analytics'
    | '/birdseye'
    | '/blog'
    | '/campaigns'
    | '/case-studies'
    | '/checkout'
    | '/contacts'
    | '/dashboard'
    | '/login'
    | '/outreach'
    | '/reset-password'
    | '/rfps'
    | '/schedule-demo'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/territory'
    | '/today'
    | '/accounts/$id'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/accounts'
    | '/api/public/calendar/$token.ics'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/affiliates'
    | '/analytics'
    | '/birdseye'
    | '/blog'
    | '/campaigns'
    | '/case-studies'
    | '/checkout'
    | '/contacts'
    | '/dashboard'
    | '/login'
    | '/outreach'
    | '/reset-password'
    | '/rfps'
    | '/schedule-demo'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/territory'
    | '/today'
    | '/accounts/$id'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/accounts/'
    | '/api/public/calendar/$token.ics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AffiliatesRoute: typeof AffiliatesRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BirdseyeRoute: typeof BirdseyeRoute
  BlogRoute: typeof BlogRouteWithChildren
  CampaignsRoute: typeof CampaignsRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ContactsRoute: typeof ContactsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OutreachRoute: typeof OutreachRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RfpsRoute: typeof RfpsRoute
  ScheduleDemoRoute: typeof ScheduleDemoRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TerritoryRoute: typeof TerritoryRoute
  TodayRoute: typeof TodayRoute
  AccountsIdRoute: typeof AccountsIdRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  ApiPublicCalendarTokenDoticsRoute: typeof ApiPublicCalendarTokenDoticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/territory': {
      id: '/territory'
      path: '/territory'
      fullPath: '/territory'
      preLoaderRoute: typeof TerritoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule-demo': {
      id: '/schedule-demo'
      path: '/schedule-demo'
      fullPath: '/schedule-demo'
      preLoaderRoute: typeof ScheduleDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfps': {
      id: '/rfps'
      path: '/rfps'
      fullPath: '/rfps'
      preLoaderRoute: typeof RfpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birdseye': {
      id: '/birdseye'
      path: '/birdseye'
      fullPath: '/birdseye'
      preLoaderRoute: typeof BirdseyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/accounts/$id': {
      id: '/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar/$token.ics': {
      id: '/api/public/calendar/$token.ics'
      path: '/api/public/calendar/$token.ics'
      fullPath: '/api/public/calendar/$token.ics'
      preLoaderRoute: typeof ApiPublicCalendarTokenDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AffiliatesRoute: AffiliatesRoute,
  AnalyticsRoute: AnalyticsRoute,
  BirdseyeRoute: BirdseyeRoute,
  BlogRoute: BlogRouteWithChildren,
  CampaignsRoute: CampaignsRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ContactsRoute: ContactsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OutreachRoute: OutreachRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RfpsRoute: RfpsRoute,
  ScheduleDemoRoute: ScheduleDemoRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TerritoryRoute: TerritoryRoute,
  TodayRoute: TodayRoute,
  AccountsIdRoute: AccountsIdRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  ApiPublicCalendarTokenDoticsRoute: ApiPublicCalendarTokenDoticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
